default_keybindings = false
notify = true
bitrate = 320
shuffle = true

[keybindings]
"n" = "next"
"Shift+n" = "next"
"p" = "previous"
"Shift+p" = "previous"
"Shift+k" = "volup 5"
"k" = "volup 5"
"Shift+j" = "voldown 5"
"j" = "voldown 5"
"-" = "voldown 1"
"+" = "volup 1"
"z" = "shuffle"
"Shift+z" = "shuffle"
"q" = "quit"
"Shift+q" = "quit"
"Space" = "playpause"
"Left" = "move left 1"
"Right" = "move right 1"
"Up" = "move up 1"
"Down" = "move down 1"
"End" = "move bottom"
"Home" = "move top"
"PageDown" = "move down 5"
"PageUp" = "move up 5"
"s" = "stop"
"Shift+s" = "stop"
"u" = "update"
"Shift+u" = "update"
"F1" = "focus queue"
"F2" = "focus search"
"F3" = "focus library"
"Ctrl+v" = "insert"
"r" = "repeat"
"Shift+r" = "repeat"
"a" = "goto artist"
"Shift+a" = "goto artist"
"Backspace" = "back"
"v" = "queue"
"Shift+v" = "queue"
"Shift+Left" = "seek -5000"
"Shift+Right" = "seek +5000"
">" = "seek +5000"
"<" = "seek -5000"
"Enter" = "play"

[theme]
background = "#00000000"
primary = "#FFFFFF"
secondary = "#55009F"
title = "#A81ED7"
playing = "#1ED760"
playing_selected = "#A81ED7"
playing_bg = "#181818"
highlight = "#1DB954"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#A81ED7"
statusbar_bg = "#A81ED7"
cmdline = "#7A9885"
cmdline_bg = "#444444"
